"""Added audit_info field

Revision ID: 165d6b082c25
Revises: d62ff66a79d3
Create Date: 2024-02-12 13:48:27.646411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '165d6b082c25'
down_revision: Union[str, None] = 'd62ff66a79d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('audit_info', sa.JSON(), nullable=True))
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'updated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('updated_by', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'audit_info')
    # ### end Alembic commands ###
