"""Change type of type

Revision ID: 57ccd5932954
Revises: a39c80eb9b1a
Create Date: 2024-02-20 10:29:25.428718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '57ccd5932954'
down_revision: Union[str, None] = 'a39c80eb9b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'type',
                    existing_type=sa.UUID(),
                    type_=sa.String(length=128),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'type',
                    existing_type=sa.String(length=128),
                    type_=sa.UUID(),
                    existing_nullable=False)
    # ### end Alembic commands ###
